"""initial

Revision ID: 965dfd07d6bc
Revises:
Create Date: 2026-04-18 10:54:13.749578

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '965dfd07d6bc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adapter_name', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('byte_offset', sa.Integer(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adapter_name', 'file_path', name='uq_adapter_file')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='severity_enum'), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_severity', 'anomalies', ['severity'], unique=False)
    op.create_index('ix_anomalies_timestamp', 'anomalies', ['timestamp'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool', sa.Enum('claude_code', 'kiro', name='tool_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_start_time', 'sessions', ['start_time'], unique=False)
    op.create_index('ix_sessions_tool', 'sessions', ['tool'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('token_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool', sa.Enum('claude_code', 'kiro', name='tool_enum'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column(
        'context_type',
        sa.Enum('chat', 'code_generation', 'code_review', 'unknown', name='context_type_enum'),
        nullable=False,
    ),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('file_types_in_context', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('file_byte_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool', 'source_file_path', 'file_byte_offset', name='uq_dedup_key')
    )
    op.create_index('ix_token_events_model', 'token_events', ['model'], unique=False)
    op.create_index('ix_token_events_session_id', 'token_events', ['session_id'], unique=False)
    op.create_index('ix_token_events_timestamp', 'token_events', ['timestamp'], unique=False)
    op.create_index('ix_token_events_tool', 'token_events', ['tool'], unique=False)
    op.create_index(
        'ix_token_events_tool_timestamp', 'token_events',
        ['tool', 'timestamp'], unique=False,
    )
    op.create_index('ix_token_events_user_id', 'token_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_events_user_id', table_name='token_events')
    op.drop_index('ix_token_events_tool_timestamp', table_name='token_events')
    op.drop_index('ix_token_events_tool', table_name='token_events')
    op.drop_index('ix_token_events_timestamp', table_name='token_events')
    op.drop_index('ix_token_events_session_id', table_name='token_events')
    op.drop_index('ix_token_events_model', table_name='token_events')
    op.drop_table('token_events')
    op.drop_table('settings')
    op.drop_index('ix_sessions_tool', table_name='sessions')
    op.drop_index('ix_sessions_start_time', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_anomalies_timestamp', table_name='anomalies')
    op.drop_index('ix_anomalies_severity', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('adapter_state')
    # ### end Alembic commands ###
